<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ8lDFps\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ8lDFps/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ8lDFps.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ8lDFps\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ8lDFps\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z8lDFps',
    'container.build_id' => '057494d2',
    'container.build_time' => 1735158552,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ8lDFps');
